### ISSUE TITLE
Unable to create package when package.json doesn't exist (.vsixmanifest instead).

### ISSUE THREAD

**Issue by patrickcurl** [MrLuje/vscode-extensions-pack-builder#11]
**Describe the bug**
Getting error on packages w/out package.json (instead they have .vsixmanifest). 

**To Reproduce**
1. Create a Pack
2. Get errors

**Expected behavior**
I should be able to add any package to extension pack.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version LTS

**Comment by MrLuje** [comment]
Can you provide an example of package with a vsixmanifest ?

**Comment by patrickcurl** [comment]
Actually, think I figured the issue.... A lot of my packages in ~/.vscode/extensions are duplicates ... the older version breaking the plugin... Might want to ignore that error instead and skip folders /packages without a package.json file. So maybe it still creates the pack but ignores extensions that aren't valid or are older and don't have package.json or weren't completely uninstalled when a package was upgraded... 

Alternately could just parse vsixmanifests where package.json isn't available to get the package name.. and other data needed, and use that to install from maybe...

**Comment by patrickcurl** [comment]
I'm going through manually deleting the older versions to see if that fixes it.
