### ISSUE TITLE
Some extensions show as %displayName%

### ISSUE THREAD

**Issue by MrLuje** [MrLuje/vscode-extensions-pack-builder#12]
![image](https://user-images.githubusercontent.com/632075/64696324-6c652500-d49e-11e9-857b-e7ee119a88bd.png)

**Comment by alexandrupetrini** [comment]
I still have this issue....

**Comment by MrLuje** [comment]
> I still have this issue....
Like for 1 or 2 ? or most of them ?

**Comment by alexandrupetrini** [comment]
> > I still have this issue....
> 
> @alexandrupetrini Like for 1 or 2 ? or most of them ?
Hello, 
Thanks for your answer. Like most of them. I don't have these issues with 1.12.
