### ISSUE TITLE
Invalid publisher name

### ISSUE THREAD

**Issue by alexandrupetrini** [MrLuje/vscode-extensions-pack-builder#7]
Hi,
I am getting this error message when I want to create a pack:

> Failed to generate the pack... Error: Command failed: npx vsce package -o build/react.vsix npx: installed 66 in 7.641s ERROR Invalid publisher name 'Alexandru C. Petrini'. Expected the identifier of a publisher, not its human-friendly name. Learn more: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#publishing-extensions

and I  don't know what to do.

**Screenshots**
![ExtensionPackError_20190430-173711](https://user-images.githubusercontent.com/44755709/56969878-b6dca980-6b6e-11e9-9fa9-965dfe61cc63.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.10

I am using VSCodium:

> Version: 1.33.1
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T17:47:02.611Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.18.0-18-generic

**Comment by MrLuje** [comment]
My bad, I'm using git user.name as publisher for the extension but obviously, it must be validated first.
Fix incoming

**Comment by MrLuje** [comment]
@alexandrupetrini You can give the last version a try (should be already available on the marketplace)

**Comment by alexandrupetrini** [comment]
Yeah, works well. Also checked "package.json"'s and name is now sanitized, characters like space and dot are replaced by minus.
